[workspace]
resolver = "2"
members = [
    "crates/cauldron",
    "crates/pattern16",
    "crates/pulse",
    "crates/version-shim",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Pyrrha Wills <pyrrha.social@gmail.com>"]

[workspace.dependencies]
cauldron = { version = "0.1.0", path = "crates/cauldron" }
pattern16 = { version = "1.0.0", path = "crates/pattern16" }

cc = "1.2.3"
faithe = "0.8.0"
libc = "0.2.168"
libloading = "0.8.6"
log = "0.4.22"
once_cell = "1.20.2"
paste = "1.0.15"
semver = "1.0.23"
serde = "1.0.216"
serde_derive = "1.0.216"
simplelog = "0.12.2"
toml = "0.8.19"
windows = "0.58.0"
windows-sys = "0.59.0"
