use bitflags::bitflags;

#[allow(non_camel_case_types)]
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EPhysicsCollisionLayerGame {
    Static = 0x1,
    Dynamic_HQ = 0x2,
    Dynamic = 0x3,
    Water_Affected = 0x4,
    Sound_occlusion = 0x5,
    Ragdoll = 0x6,
    Gravity_pockets = 0x32,
    Static_shoot_through = 0x33,
    Dynamic_shoot_through = 0x34,
    Bullet_blocker = 0x35,
    Bullet_blocker_raycast = 0x36,
    Trigger = 0x37,
    Trigger_raycast = 0x38,
    Heavy_Ragdoll = 0x39,
    Player_Collision = 0x7,
    Player = 0x8,
    AI_or_Remote_Player = 0x9,
    Humanoid_blocker = 0xA,
    Player_blocker = 0xB,
    Foot_placement = 0xC,
    Dynamic_but_humanoid = 0xD,
    Humanoid_raycast_movement = 0xE,
    Humanoid_Ragdoll = 0xF,
    Ragdoll_no_collision_vs_static = 0x10,
    Impact_effect_Event_Query = 0x11,
    Combat_AI = 0x12,
    Humanoid_movement_helper = 0x13,
    Projectile = 0x14,
    Dynamic_HQ_Pullable_Shoot_Through = 0x15,
    Dynamic_Pullable = 0x16,
    AI_static = 0x17,
    Flying_Mount_blocker_raycast = 0x18,
    vs_Humanoids = 0x19,
    Dynamic_HQ_Pullable = 0x1A,
    Flying_Mount = 0x1B,
    Ragdoll_stopper = 0x1C,
    Mortally_wounded = 0x1D,
    Dynamic_HQ_but_humanoid = 0x1E,
    Proxy_player = 0x1F,
    Blocks_AI_Hearing = 0x20,
    Pullables_blocker = 0x21,
    Flying_Mount_blocker = 0x22,
    Dynamic_Pullables_blocker = 0x23,
    Blocks_vision = 0x24,
    Player_Ragdoll = 0x25,
    Dynamic_No_Collision = 0x26,
    Blocks_AI_Hearing_Raycast = 0x27,
    Weapon_blocker = 0x28,
    Dynamic_blocker = 0x29,
    Focus_Object = 0x2A,
    Focus_Object_Raycast = 0x2B,
    Static_But_Humanoid = 0x2C,
    vs_Bullet_Blocker_Only = 0x2D,
    Particles_Collision = 0x2E,
    Ray_vs_Static = 0x2F,
    Special_Object = 0x30,
    Static_But_Humanoid_but_NavMesh = 0x31,
    Camera_Obstruction = 0x3A,
    Navigation_Mesh = 0x3B,
    Vault_Query = 0x3C,
    SVO_Query = 0x3D,
    SVO_Blocker = 0x3E,
    Special_Object_Blocker = 0x3F,
    Navigation_Mesh_Hard_Obstacle = 0x40,
    Camera_Blocker_Raycast = 0x41,
    Camera_Collision = 0x42,
    Static_but_Navigation_Mesh = 0x43,
    Dynamic_but_Navigation_Mesh = 0x44,
    Foot_Support = 0x45,
    Dynamic_HQ_but_FOOT_Support = 0x46,
    Humanoid_raycast_movement_no_ragdoll = 0x47,
    Camera_Blocker = 0x48,
    Player_and_Camera_Blocker = 0x49,
    Dynamic_Shoot_Through__No_Camera = 0x4A,
    Air_Movement_Blocker = 0x4B,
    Dynamic_HQ_but_human_and_Air_Movement = 0x4C,
    Dynamic_But_Ragdolls = 0x4D,
    Foliage = 0x4E,
    Foliage_Query = 0x4F,
    Soft_Lock_Blocker = 0x50,
    Soft_Lock_Blocker_Query = 0x51,
    Dynamic_but_FOOT_Support = 0x52,
    Projectile_and_vs_Bullet_Blocker = 0x53,
    Static_Debug = 0x54,
    Dynamic_Debug = 0x55,
    Lightbake_Visibility = 0x56,
    Debug_Draw = 0x57,
    Density_Debug = 0x58,
    No_Collision = 0x7F,
}

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct EEntityFlags : i32
    {
        const None = 0;
        const Changed = 0x1;
        const Visible = 0x2;
        const Sleeping = 0x200;
    }
}
