/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    #[link_name = "\u{1}?scan@Pat16@@YAPEBXPEBX_KPEBD@Z"]
    pub fn Pat16_scan(
        start: *const ::std::os::raw::c_void,
        end: usize,
        signature: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_void;
}
