[package]
name = "pulse"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A Cauldron plugin to dump GGRTTI types."

[lib]
crate-type = ["cdylib"]

[dependencies]
cauldron.workspace = true
faithe.workspace = true
log.workspace = true
simplelog = {workspace = true, features = ["paris"]}
windows = { workspace = true, features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_SystemInformation", "Win32_System_SystemServices"] }
pelite = "0.10.0"
libc.workspace = true