[package]
name = "cauldron"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A decima engine plugin loader."

[lib]
crate-type = [ "cdylib", "lib" ]

[dependencies]
libloading.workspace = true
libc.workspace = true
log.workspace = true
once_cell.workspace = true
semver.workspace = true
simplelog = { workspace = true, features = ["paris"] }
windows-sys = { workspace = true, features = ["Win32_System_Console"] }
tabled = "0.17.0"
egui.workspace = true
focus.workspace = true
egui_extras = { workspace = true, features = ["default", "image"] }
catppuccin-egui = { version = "5.3.1", default-features = false, features = ["egui29"] }
image = { version = "0.25.5", features = ["avif", "bmp", "dds", "exr", "ff", "gif", "hdr", "ico", "jpeg", "png", "pnm", "qoi", "tga", "tiff", "webp"] }