name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add x86_64-pc-windows-msvc Target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --verbose
